/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'n-tange' at '15/11/15 1:26' with Gradle 2.8
 *
 * @author n-tange, @date 15/11/15 1:26
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
}
